spring.application.name=ti

spring.datasource.url=jdbc:postgresql://localhost:5432/cyber
spring.datasource.username=postgres
spring.datasource.password=securebyte26.
#se deixar espaco depois do ponto crasha tudo :))

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#deixar create pra criar algo no bd
spring.jpa.show-sql=true
