spring.application.name=ti

spring.datasource.url=jdbc:postgresql://localhost:5432/cyber
spring.datasource.username=postgres
spring.datasource.password=securebyte26.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true